### PR TITLE
Add puppet-lint Docker image

### PR DESCRIPTION
**Pull request by stevenzeck**

### CODE REVIEW

**Comment by stevenzeck** [comment]
I'll update readme when it's published to Docker Hub.

**Comment by Glavin001** [comment]
Docker Hub link: https://hub.docker.com/r/unibeautify/puppet-lint/

**Review by Glavin001 — CHANGES_REQUESTED** [review]
Update README.

**Comment by stevenzeck** [comment]
Done

**Review by Glavin001 — APPROVED** [review]

**Comment by Glavin001** [comment]
Thanks!

**Pull request merged**
