### PR TITLE
update rubocop

### PR DESCRIPTION
**Pull request by stepahn**
* updated rubocop to 0.64.0
* added rubocop-rspec 1.32.0
* use multi stage build for smaller image size

this should also fix #34

### CODE REVIEW

**Comment by Glavin001** [comment]
Looks good! Please re-enable `rubocop` for Travis CI: https://github.com/Unibeautify/docker-beautifiers/blob/master/.travis.yml#L18
Thank you for contributing!

**Review by Glavin001 — CHANGES_REQUESTED** [review]
Looks good! Please re-enable `rubocop` for Travis CI: https://github.com/Unibeautify/docker-beautifiers/blob/master/.travis.yml#L18
Thank you for contributing!

**Comment by stepahn** [comment]
sure think… re-enabled travis as requested. Let me know if you require any other modifications.

**Review by Glavin001 — APPROVED** [review]

**Comment by Glavin001** [comment]
Thanks for contributing @stepahn !

**Pull request merged**
